version: "3.8"

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.9.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - opensearch-node1

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
